---

install:
  - ./ci/install_deps.sh
  - PATH=~/bin:$PATH
  - source ~/.gimme/envs/latest.env
  - export DEV_KUBECONFIG=~/.kube/$(cat ~/kubernaut-claim.txt).yaml

language: generic

branches:
  only:
  - master
  - /^v.*$/

script: 
  - cd ci && ./run_test.sh

after_script:
  - kubernaut claims delete $(cat ~/kubernaut-claim.txt)
