{{- if and .Values.licenseKey.createSecret .Values.enableAES }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ambassador.fullname" . }}-edge-stack
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  license-key: {{- if .Values.licenseKey.value }} {{ .Values.licenseKey.value | b64enc }} {{- else }} "" {{- end }}
{{- end }}
