{{- if and .Values.enableAES .Values.servicePreview.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: telepresence-proxy
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- end }}
    product: aes
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: telepresence-proxy
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: telepresence-proxy
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: telepresence-proxy
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "traffic-manager" ]
        env:
        - name: AMBASSADOR_LICENSE_FILE
          value: /.config/ambassador/license-key
        ports:
        - name: sshd
          containerPort: 8022
        volumeMounts:
        - mountPath: /tmp/ambassador-pod-info
          name: pod-info
        - mountPath: /.config/ambassador
          name: ambassador-edge-stack-secrets
          readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
      volumes:
      - downwardAPI:
          items:
          - fieldRef:
              fieldPath: metadata.labels
            path: labels
        name: pod-info
      - name: ambassador-edge-stack-secrets
        secret:
          secretName: {{ include "ambassador.fullname" . }}-edge-stack
---
apiVersion: v1
kind: Service
metadata:
  name: telepresence-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: telepresence-proxy
    app.kubernetes.io/part-of: {{ .Release.Name }}
    helm.sh/chart: {{ include "ambassador.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.deploymentTool }}
    app.kubernetes.io/managed-by: {{ .Values.deploymentTool }}
    {{- else }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- end }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: telepresence-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: sshd
    protocol: TCP
    port: 8022
  - name: api
    protocol: TCP
    port: 8081
{{- end }}