
# https://github.com/helm/chart-testing-action/blob/master/README.md
name: Lint and Test Charts
on: pull_request
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: lint

      - name: Create kind cluster
        uses: datawire/cluster-providers@master
        with:
            provider: k3d
            action: create
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0-rc.1
        with:
          command: install
